// Seed-fallback templates for the merchandising module.
// Used during development and when middleware-pushed templates are not yet available.
// When backoffice publishes templates via /sync/audit_templates, these get
// upserted on top by version (newer versions of the same id replace).
//
// Each template covers a representative subset of KPIs from
// docs/merchandising_module_spec.md §5.4 for that outlet type.
// Final question library is owned by the backoffice (spec §8.1).

const RETAIL_TEMPLATE = {
  id: 'tmpl-retail-v1',
  outlet_type: 'retail',
  version: 1,
  name: 'Аудит ритейла v1',
  active: 1,
  scoring: {
    blocks: {
      availability: 25, layout: 20, cooler: 15, price: 10,
      posm: 10, horeca: 0, staff: 5, process: 15,
    },
  },
  questions: [
    {
      id: 'retail.availability.osa',
      block: 'availability',
      type: 'composite',
      kpi_codes: ['OSA', 'OOS'],
      title: 'Наличие SKU из MML',
      hint: 'Отметьте наличие каждого SKU из обязательной матрицы',
      required: true,
      sub: { kind: 'mml_checklist' },
    },
    {
      id: 'retail.availability.fifo',
      block: 'availability',
      type: 'bool',
      kpi_codes: ['FIFO'],
      title: 'Соблюдение FIFO',
      required: true,
    },
    {
      id: 'retail.layout.shelf_full',
      block: 'layout',
      type: 'photo_required',
      photo_type: 'shelf_full',
      kpi_codes: ['SOS', 'BLOCKS'],
      title: 'Фото полки целиком',
      hint: 'Снимок должен включать всю секцию категории',
      min_photos: 1,
      max_photos: 3,
      required: true,
    },
    {
      id: 'retail.layout.facings_ours',
      block: 'layout',
      type: 'int',
      kpi_codes: ['SOS'],
      title: 'Фейсингов наших SKU',
      min: 0,
      required: true,
      sub: { facings_total_qid: 'retail.layout.facings_total' },
    },
    {
      id: 'retail.layout.facings_total',
      block: 'layout',
      type: 'int',
      title: 'Фейсингов всего в категории',
      min: 1,
      required: true,
    },
    {
      id: 'retail.layout.eye_level',
      block: 'layout',
      type: 'bool',
      kpi_codes: ['EYE_LEVEL'],
      title: 'Наши SKU на уровне глаз',
      required: false,
    },
    {
      id: 'retail.layout.plano',
      block: 'layout',
      type: 'select',
      kpi_codes: ['PLANO_COMPLIANCE'],
      title: 'Соответствие планограмме',
      options: [
        { value: 'full', label: 'Полное' },
        { value: 'partial', label: 'Частичное' },
        { value: 'none', label: 'Не соответствует' },
        { value: 'no_plano', label: 'Планограмма отсутствует' },
      ],
      required: true,
    },
    {
      id: 'retail.price.tag_presence',
      block: 'price',
      type: 'decimal',
      kpi_codes: ['PRICE_TAG_PRESENCE'],
      title: 'Доля SKU с ценниками, %',
      min: 0,
      max: 100,
      required: true,
    },
    {
      id: 'retail.price.tag_photo',
      block: 'price',
      type: 'photo',
      photo_type: 'price_tag',
      kpi_codes: ['PRICE_TAG_CORRECTNESS', 'PRICE_COMPLIANCE'],
      title: 'Фото ценников',
      min_photos: 1,
      max_photos: 5,
      required: false,
    },
    {
      id: 'retail.price.compliance',
      block: 'price',
      type: 'select',
      kpi_codes: ['PRICE_COMPLIANCE'],
      title: 'Цена в пределах РРЦ',
      options: [
        { value: 'within', label: 'В пределах' },
        { value: 'below', label: 'Ниже РРЦ' },
        { value: 'above', label: 'Выше РРЦ' },
      ],
      required: true,
    },
    {
      id: 'retail.posm.placement',
      block: 'posm',
      type: 'multiselect',
      kpi_codes: ['POSM_PLACEMENT'],
      title: 'POSM в торговом зале',
      options: [
        { value: 'wobbler', label: 'Воблер' },
        { value: 'shelftalker', label: 'Шелфтокер' },
        { value: 'poster', label: 'Постер' },
        { value: 'standee', label: 'Стэнди' },
        { value: 'sticker', label: 'Стикер' },
      ],
      required: false,
    },
    {
      id: 'retail.posm.condition',
      block: 'posm',
      type: 'select',
      kpi_codes: ['POSM_CONDITION'],
      title: 'Состояние POSM',
      options: [
        { value: '5', label: '5 — отличное' },
        { value: '4', label: '4 — хорошее' },
        { value: '3', label: '3 — приемлемое' },
        { value: '2', label: '2 — повреждено' },
        { value: '1', label: '1 — непригодно' },
      ],
      required: false,
    },
    {
      id: 'retail.posm.photo',
      block: 'posm',
      type: 'photo',
      photo_type: 'posm',
      kpi_codes: ['POSM_PLACEMENT', 'POSM_CONDITION'],
      title: 'Фото POSM',
      max_photos: 3,
      required: false,
    },
    {
      id: 'retail.process.notes',
      block: 'process',
      type: 'text',
      title: 'Комментарий мерчендайзера',
      required: false,
    },
  ],
};

const KIOSK_TEMPLATE = {
  id: 'tmpl-kiosk-v1',
  outlet_type: 'kiosk',
  version: 1,
  name: 'Аудит киоска v1',
  active: 1,
  scoring: {
    blocks: {
      availability: 20, layout: 10, cooler: 30, price: 15,
      posm: 10, horeca: 0, staff: 0, process: 15,
    },
  },
  questions: [
    {
      id: 'kiosk.availability.osa',
      block: 'availability',
      type: 'composite',
      kpi_codes: ['OSA'],
      title: 'Наличие SKU из MML',
      sub: { kind: 'mml_checklist' },
      required: true,
    },
    {
      id: 'kiosk.cooler.interior_photo',
      block: 'cooler',
      type: 'photo_required',
      photo_type: 'cooler_interior',
      kpi_codes: ['SOC', 'PURE_COOLER', 'FILL_RATE'],
      title: 'Фото холодильника изнутри',
      min_photos: 1,
      max_photos: 2,
      required: true,
    },
    {
      id: 'kiosk.cooler.facings_ours',
      block: 'cooler',
      type: 'int',
      kpi_codes: ['SOC'],
      title: 'Фейсингов наших SKU в холодильнике',
      min: 0,
      required: true,
      sub: { facings_total_qid: 'kiosk.cooler.facings_total' },
    },
    {
      id: 'kiosk.cooler.facings_total',
      block: 'cooler',
      type: 'int',
      title: 'Фейсингов всего в холодильнике',
      min: 1,
      required: true,
    },
    {
      id: 'kiosk.cooler.pure',
      block: 'cooler',
      type: 'bool',
      kpi_codes: ['PURE_COOLER'],
      title: 'Чистый холодильник (без конкурентов)',
      required: true,
    },
    {
      id: 'kiosk.cooler.fill_rate',
      block: 'cooler',
      type: 'decimal',
      kpi_codes: ['FILL_RATE'],
      title: 'Заполненность холодильника, %',
      min: 0, max: 100,
      required: true,
    },
    {
      id: 'kiosk.cooler.branding',
      block: 'cooler',
      type: 'bool',
      kpi_codes: ['BRANDING_COOLER'],
      title: 'Брендирование холодильника целое',
      required: true,
    },
    {
      id: 'kiosk.cooler.temp',
      block: 'cooler',
      type: 'int',
      kpi_codes: ['COOLER_TEMP'],
      title: 'Температура (°C)',
      min: -10, max: 30,
      required: false,
    },
    {
      id: 'kiosk.price.compliance',
      block: 'price',
      type: 'select',
      kpi_codes: ['PRICE_COMPLIANCE'],
      title: 'Цена в пределах РРЦ',
      options: [
        { value: 'within', label: 'В пределах' },
        { value: 'below', label: 'Ниже' },
        { value: 'above', label: 'Выше' },
      ],
      required: true,
    },
    {
      id: 'kiosk.posm.placement',
      block: 'posm',
      type: 'multiselect',
      kpi_codes: ['POSM_PLACEMENT'],
      title: 'POSM на ТТ',
      options: [
        { value: 'sticker', label: 'Стикер' },
        { value: 'poster', label: 'Постер' },
        { value: 'wobbler', label: 'Воблер' },
        { value: 'standee', label: 'Стэнди' },
      ],
      required: false,
    },
    {
      id: 'kiosk.process.notes',
      block: 'process',
      type: 'text',
      title: 'Комментарий мерчендайзера',
      required: false,
    },
  ],
};

const HORECA_BAR_TEMPLATE = {
  id: 'tmpl-horeca-bar-v1',
  outlet_type: 'horeca_bar',
  version: 1,
  name: 'Аудит бара v1',
  active: 1,
  scoring: {
    blocks: {
      availability: 15, layout: 10, cooler: 5, price: 5,
      posm: 15, horeca: 30, staff: 10, process: 10,
    },
  },
  questions: [
    {
      id: 'bar.menu.listing',
      block: 'horeca',
      type: 'composite',
      kpi_codes: ['MENU_LISTING'],
      title: 'Наши SKU в меню/барной карте',
      sub: { kind: 'mml_checklist' },
      required: true,
    },
    {
      id: 'bar.menu.photo',
      block: 'horeca',
      type: 'photo_required',
      photo_type: 'menu',
      kpi_codes: ['MENU_LISTING', 'FEATURED_POS'],
      title: 'Фото меню/барной карты',
      min_photos: 1,
      max_photos: 3,
      required: true,
    },
    {
      id: 'bar.menu.featured',
      block: 'horeca',
      type: 'bool',
      kpi_codes: ['FEATURED_POS'],
      title: 'Наши SKU выделены в меню (специальное место)',
      required: false,
    },
    {
      id: 'bar.availability.back_bar',
      block: 'availability',
      type: 'photo_required',
      photo_type: 'shelf_full',
      kpi_codes: ['OSA'],
      title: 'Фото back-bar',
      min_photos: 1,
      max_photos: 2,
      required: true,
    },
    {
      id: 'bar.glassware.branded',
      block: 'horeca',
      type: 'composite',
      kpi_codes: ['BRANDED_GLASSWARE'],
      title: 'Брендированная посуда',
      sub: { kind: 'glassware_check' },
      required: false,
    },
    {
      id: 'bar.glassware.photo',
      block: 'horeca',
      type: 'photo',
      photo_type: 'glassware',
      kpi_codes: ['BRANDED_GLASSWARE'],
      title: 'Фото подачи (бокал/стакан)',
      max_photos: 3,
      required: false,
    },
    {
      id: 'bar.posm.activations',
      block: 'posm',
      type: 'multiselect',
      kpi_codes: ['POSM_PLACEMENT', 'PROMO_EXEC'],
      title: 'Активации/POSM в баре',
      options: [
        { value: 'tent_card', label: 'Tent-card' },
        { value: 'menu_holder', label: 'Меню-холдер' },
        { value: 'coaster', label: 'Подставка' },
        { value: 'banner', label: 'Баннер' },
      ],
      required: false,
    },
    {
      id: 'bar.process.notes',
      block: 'process',
      type: 'text',
      title: 'Комментарий мерчендайзера',
      required: false,
    },
  ],
};

const HORECA_CAFE_TEMPLATE = {
  id: 'tmpl-horeca-cafe-v1',
  outlet_type: 'horeca_cafe',
  version: 1,
  name: 'Аудит кафе/ресторана v1',
  active: 1,
  scoring: {
    blocks: {
      availability: 15, layout: 5, cooler: 10, price: 5,
      posm: 15, horeca: 35, staff: 5, process: 10,
    },
  },
  questions: [
    {
      id: 'cafe.menu.listing',
      block: 'horeca',
      type: 'composite',
      kpi_codes: ['MENU_LISTING'],
      title: 'Наши SKU в меню',
      sub: { kind: 'mml_checklist' },
      required: true,
    },
    {
      id: 'cafe.menu.photo',
      block: 'horeca',
      type: 'photo_required',
      photo_type: 'menu',
      kpi_codes: ['MENU_LISTING'],
      title: 'Фото меню',
      min_photos: 1,
      max_photos: 3,
      required: true,
    },
    {
      id: 'cafe.serve.branded',
      block: 'horeca',
      type: 'bool',
      kpi_codes: ['BRANDED_GLASSWARE'],
      title: 'Подача в брендированной посуде',
      required: false,
    },
    {
      id: 'cafe.recipe.compliance',
      block: 'horeca',
      type: 'select',
      kpi_codes: ['RECIPE_COMPLIANCE'],
      title: 'Соответствие рецептуре',
      options: [
        { value: 'full', label: 'Полное' },
        { value: 'partial', label: 'Частичное' },
        { value: 'no', label: 'Нарушение' },
        { value: 'unknown', label: 'Не проверял' },
      ],
      required: false,
    },
    {
      id: 'cafe.posm.visibility',
      block: 'posm',
      type: 'multiselect',
      kpi_codes: ['POSM_PLACEMENT'],
      title: 'POSM в зале',
      options: [
        { value: 'tent_card', label: 'Tent-card' },
        { value: 'menu_insert', label: 'Вкладыш в меню' },
        { value: 'banner', label: 'Баннер' },
        { value: 'sticker', label: 'Стикер' },
      ],
      required: false,
    },
    {
      id: 'cafe.process.notes',
      block: 'process',
      type: 'text',
      title: 'Комментарий мерчендайзера',
      required: false,
    },
  ],
};

export const SEED_AUDIT_TEMPLATES = [
  RETAIL_TEMPLATE,
  KIOSK_TEMPLATE,
  HORECA_BAR_TEMPLATE,
  HORECA_CAFE_TEMPLATE,
];
